cmake_minimum_required(VERSION 3.8)
project(bot_interfaces)

find_package(ament_cmake REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(std_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)

rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/VLMResult.msg"
  "msg/VelocityCommand.msg"
  "srv/VLMQuery.srv"
  DEPENDENCIES std_msgs sensor_msgs builtin_interfaces
)

ament_package()
